# Generated by Django 4.0 on 2021-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=120, unique=True)),
                ('productname', models.CharField(max_length=120, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('out of stock', 'out of stock'), ('active', 'active'), ('inactive', 'inactive')], default='available', max_length=120)),
            ],
        ),
    ]
