# Generated by Django 4.0 on 2021-12-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_stock_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
